@echo off
echo Starting Unified Ticketing ^& Attendance System...

echo Starting Backend (Port 5000)...
start "Unified Backend" /D "backend" npm run dev

echo Starting Frontend (Port 5173)...
start "Unified Frontend" npm run dev

echo Application starting...
