USE ttl_support_tool;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS profile_picture LONGTEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS home_address TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS aadhar_number VARCHAR(50) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS pan_number VARCHAR(50) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS blood_group VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS emergency_contact VARCHAR(20) DEFAULT NULL;

-- Verify columns structure
DESCRIBE users;
